FROM nginx:1.25-alpine

# Eliminar config por defecto y poner la nuestra
RUN rm /etc/nginx/conf.d/default.conf
COPY dashboard/nginx.conf /etc/nginx/conf.d/default.conf

# Copiar archivos estáticos
COPY dashboard/public/ /usr/share/nginx/html/

EXPOSE 80
