# Generated by hand for InciTrack

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django.contrib.auth.models
import tickets.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(blank=True, max_length=150)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('rol', models.CharField(choices=[('admin', 'Admin TI'), ('jefe', 'Jefe de Cuenta'), ('supervisor', 'Supervisor')], default='supervisor', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user_permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='Identificador técnico sin espacios ni tildes', max_length=100, unique=True)),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='Orden de aparición en formularios')),
                ('activa', models.BooleanField(default=True)),
                ('requiere_plataforma_bi', models.BooleanField(default=False, help_text="Activar solo para 'Plataformas BI'. Muestra selector PowerBI/QlikView.")),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('jefe', models.ForeignKey(blank=True, limit_choices_to={'rol': 'jefe'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuentas_como_jefe', to='tickets.usuario')),
                ('supervisores', models.ManyToManyField(blank=True, limit_choices_to={'rol': 'supervisor'}, related_name='cuentas_asignadas', to='tickets.usuario')),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='tickets.categoria')),
            ],
            options={
                'verbose_name': 'Subcategoría',
                'verbose_name_plural': 'Subcategorías',
                'ordering': ['orden', 'nombre'],
                'unique_together': {('categoria', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('en_proceso', 'En Proceso'), ('resuelto', 'Resuelto'), ('cerrado', 'Cerrado')], default='abierto', max_length=20)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=20)),
                ('plataforma_bi', models.CharField(blank=True, choices=[('PowerBI', 'Power BI'), ('QlikView', 'QlikView')], help_text='Obligatorio cuando la categoría es Plataformas BI', max_length=20, null=True)),
                ('tipo_incidencia', models.CharField(blank=True, default='', help_text='[LEGACY] Valor de clasificación para tickets creados antes de v2', max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('fue_reasignado', models.BooleanField(default=False, help_text='True cuando el responsable TI fue cambiado manualmente tras la asignación automática.')),
                ('asignado_a', models.ForeignKey(blank=True, limit_choices_to={'rol': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_asignados', to='tickets.usuario')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tickets.categoria')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets_creados', to='tickets.usuario')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tickets.cuenta')),
                ('subcategoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.subcategoria')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='NotificacionServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(blank=True, default='', help_text='[LEGACY] Valor anterior a v2', max_length=100)),
                ('emails_cc', models.TextField(blank=True, help_text='Emails CC separados por coma')),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(blank=True, help_text='Dejar vacío para notificación global', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='tickets.categoria')),
                ('subcategoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='tickets.subcategoria')),
                ('usuarios', models.ManyToManyField(blank=True, limit_choices_to={'rol': 'admin'}, related_name='notificaciones_servicio', to='tickets.usuario')),
            ],
            options={
                'verbose_name': 'Notificación de Servicio',
                'verbose_name_plural': 'Notificaciones de Servicio',
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('interno', models.BooleanField(default=False, help_text='Visible solo para admin y jefe. Invisible para supervisor.')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comentarios', to='tickets.usuario')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Adjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_original', models.CharField(max_length=255)),
                ('nombre_guardado', models.CharField(max_length=255)),
                ('archivo', models.FileField(upload_to=tickets.models.adjunto_upload_path)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Adjunto',
                'verbose_name_plural': 'Adjuntos',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionSLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plataforma_bi', models.CharField(blank=True, choices=[('PowerBI', 'Power BI'), ('QlikView', 'QlikView')], help_text='Aplicar solo cuando categoría es Plataformas BI', max_length=20, null=True)),
                ('tiempo_respuesta_minutos', models.PositiveIntegerField(help_text='Tiempo máximo de primera respuesta en minutos (ej: 60 = 1 hora)')),
                ('tiempo_cierre_minutos', models.PositiveIntegerField(default=0, help_text='Tiempo máximo para cerrar el ticket en minutos totales')),
                ('descripcion', models.CharField(blank=True, help_text='Notas opcionales sobre este SLA', max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slas', to='tickets.categoria')),
                ('subcategoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slas', to='tickets.subcategoria')),
            ],
            options={
                'verbose_name': 'Configuración SLA',
                'verbose_name_plural': 'Configuraciones SLA',
                'ordering': ['categoria__orden', 'categoria__nombre', 'subcategoria__nombre'],
                'unique_together': {('categoria', 'subcategoria', 'plataforma_bi')},
            },
        ),
    ]
